name: Generate Snake Animation

on:
  schedule:
    # Runs every 12 hours
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write 

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: roshinit-a
          
          # We are back to only creating the one light snake file
          outputs: dist/snake.svg
          
      - name: Push to repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # We only need to add the one file
          git add dist/snake.svg
          
          git commit -m "feat: update snake animation" || exit 0
          git push
